config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index', as: 'home'

  get 'smart_conversation', to: 'home#smart_conversation', as: 'smart_conversation'

  post 'problem', to: 'problem#create', as: 'problems'

  post 'transcript', to: 'transcript#create', as: 'transcripts'
  post 'dialogue', to: 'transcript#create_dialogue', as: 'dialogues'
  get 'dialogues', to: 'transcript#dialogues', as: 'get_dialogues'

  get 'transcript_users', to: 'transcript#users', as: 'transcript_users'

  resources :topic

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dialogue.rb
class Dialogue < ApplicationRecord
  belongs_to :transcript

  def self.to_csv(dialogues)
    attributes = %w{user sentence word_detected created_at}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      dialogues.each do |dialogue|
        csv << attributes.map { |attr| dialogue.send(attr) }
      end
    end
  end
end

app/models/problem.rb
class Problem < ApplicationRecord

  has_attached_file :document
  validates_attachment :document, :content_type => { :content_type => %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document) }


  def url
    document.url
  end

  def name
    document.original_filename
  end

end

app/models/topic.rb
class Topic < ApplicationRecord
  serialize :words, Array
end

app/models/transcript.rb
class Transcript < ApplicationRecord
  has_many :dialogues
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def smart_conversation
    @problems = Problem.all
    @problem = Problem.new

    @transcript = Transcript.new
    @transcripts = Transcript.all

    @topic = Topic.new
    @topics = Topic.all
  end

  def index
  end
end

app/controllers/problem_controller.rb
class ProblemController < ApplicationController

  def create
    @problem = Problem.create(problem_params)
    redirect_to home_path
  end

  private
  def problem_params
    params.require(:problem).permit(:document)
  end
end

app/controllers/speech_recognition_controller.rb
class SpeechRecognitionController < ApplicationController
  def index
  end
end

app/controllers/topic_controller.rb
class TopicController < ApplicationController

  def create
    Topic.create(name: topic_params[:name], words: get_words())
    redirect_to home_path
  end

  def index
  end

  def show
    render json: Topic.find(topic_id)
  end

  private

  def topic_id
    params[:id]
  end

  def get_words
    topic_params[:words].split(',').map(&:strip).map(&:downcase)
  end

  def topic_params
    params.require(:topic).permit(:name, :words)
  end

end

app/controllers/transcript_controller.rb
class TranscriptController < ApplicationController

  def create
    Transcript.create(transcript_params)
    redirect_to home_path
  end

  def create_dialogue
    Dialogue.create(dialogue_params)
  end

  def users
    transcript = Transcript.where(users_params)[0]
    render json: [transcript.user1, transcript.user2]
  end

  def dialogues
    transcript = Transcript.where(dialogues_params)[0]
    @dialogues = transcript.dialogues

    respond_to do |format|
      format.json { render json: @dialogues, status: :ok }
      format.csv { send_data Dialogue.to_csv(@dialogues), filename: "transcript-#{transcript.name}-#{Date.today}.csv" }
    end
  end

  private
  def dialogues_params
    params.require(:transcript).permit(:id)
  end

  def transcript_params
    params.require(:transcript).permit(:name, :user1, :user2)
  end

  def users_params
    params.require(:transcript).permit(:id)
  end

  def dialogue_params
    params.require(:dialogue).permit(:transcript_id, :user, :sentence, :word_detected)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/problem_helper.rb
module ProblemHelper
end

app/helpers/speech_recognition_helper.rb
module SpeechRecognitionHelper
end

app/helpers/topic_helper.rb
module TopicHelper
end

app/helpers/transcript_helper.rb
module TranscriptHelper
end

app/views/home/_smart_conversation_setup.html.erb
<div class="mdl-cell mdl-cell--2-col">
  <button id="show-setup-dialog" type="button" data-bind="click: function(){ showDialog('setup') }"
          class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored setup-btn">
    Setup
  </button>
</div>
<div class="mdl-cell mdl-cell--2-col" data-bind="with: conversation">
  <button id="start-conversation" type="button"
          class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored start-stop-btn"
          data-bind="click: toggleConversation, text: startStop, css: {'mdl-color--red-700': startStop() == 'Stop', 'mdl-color--green-700': startStop() == 'Start' }, enable: $parent.selectedTopic()">
  </button>
</div>
<div class="mdl-cell mdl-cell--2-col">
  <div class="mdl-typography--headline mdl-typography--text-left" data-bind="visible: selectedUser"> <!-- Appears when you select something -->
    <span class="label-text">I am:</span>
    <span data-bind="text: selectedUser() ? selectedUser().name : 'unknown' "></span>.
  </div>
</div>
<div class="mdl-cell mdl-cell--3-col">
  <div class="mdl-typography--headline mdl-typography--text-left" data-bind="visible: selectedTopic"> <!-- Appears when you select something -->
    <span class="label-text">Topic:</span>
    <span data-bind="text: selectedTopic() ? selectedTopic().name : 'unknown' "></span>.
  </div>
</div>
<div class="mdl-cell mdl-cell--3-col">
  <button id="show-transcript" data-bind="click: function(){ showDialog('transcript') }"
          class="mdl-button mdl-js-button show-transcript-btn">
    Show Transcript
  </button>
</div>


<dialog class="mdl-dialog" id="setup-dialog">
  <h4 class="mdl-dialog__title mdl-typography--text-center">Speech recognition setup</h4>
  <div class="mdl-dialog__content mdl-typography--text-left">

    <div class="mdl-tabs mdl-js-tabs mdl-js-ripple-effect">
      <div class="mdl-tabs__tab-bar">
        <a href="#conversation-panel" class="mdl-tabs__tab is-active">Conversation</a>
        <a href="#upload-panel" class="mdl-tabs__tab">Setup</a>
      </div>

      <div class="mdl-tabs__panel is-active" id="conversation-panel">
        <p>

          Topic:
          <%= select_tag 'selected_topic',
                         options_from_collection_for_select(@topics, 'id', 'name'),
                         {'data-bind' => 'event: { change: updateWords}', class: 'custom-select'}
          %>
        </p>


        <p>
          Timeout:
          <input class="custom-text-field" type="number" id="timeout" data-bind="value: timeout"> secs
        </p>

        <p>
          Problem:
          <%= select_tag 'problem', options_from_collection_for_select(@problems, 'url', 'name'), class: 'custom-select' %>
        </p>
        <p>
          Transcript:
          <%= select_tag 'transcript',
                         options_from_collection_for_select(@transcripts, 'id', 'name'),
                         {'data-bind' => 'event: { change: updateUsers}', class: 'custom-select'}
          %>
        </p>
        <p>

          User:
          <select class="custom-select"
                  data-bind="options: users,
                       optionsText: 'name',
                       value: selectedUser,
                       optionsCaption: 'Choose...'"></select>
        </p>
      </div>
      <div class="mdl-tabs__panel" id="upload-panel">


        <div class="mdl-grid">
          <div class="mdl-cell mdl-cell--12-col">
            <h4>New problem statement</h4>
            <%= form_for @problem, url: problems_path, html: {class: 'mdl-grid', multipart: true} do |form| %>

                <div class="mdl-cell mdl-cell--6-col">
                  <div class="upload-container">
                    <span class="upload-btn">Choose file</span>
                    <%= form.file_field :document, class: 'chooser' %>
                  </div>
                </div>
                <div class="mdl-cell mdl-cell--6-col">
                  <%= submit_tag 'Submit', class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>
                </div>
            <% end %>
          </div>
          <div class="mdl-cell mdl-cell--6-col">

            <h4>Setup Transcript</h4>

            <%= form_for @transcript, remote: true, url: transcripts_path, html: {multipart: true} do |f| %>
                <div class="mdl-grid">
                  <div class="mdl-cell mdl-cell--12-col">
                    <%= f.label :name %>
                    <%= f.text_field :name, class: 'custom-text-field' %>
                  </div>
                  <div class="mdl-cell mdl-cell--12-col">
                    <%= f.label :user1 %>
                    <%= f.text_field :user1, class: 'custom-text-field' %>
                  </div>
                  <div class="mdl-cell mdl-cell--12-col">
                    <%= f.label :user2 %>
                    <%= f.text_field :user2, class: 'custom-text-field' %>
                  </div>
                  <div class="mdl-cell mdl-cell--12-col">
                    <%= submit_tag 'Submit', class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>
                  </div>
                </div>
            <% end %>
          </div>
          <div class="mdl-cell mdl-cell--6-col">

            <h4>Setup Topics</h4>

            <%= form_for @topic, remote: true, url: topic_index_path, html: {multipart: true} do |f| %>
                <div class="mdl-grid">
                  <div class="mdl-cell mdl-cell--12-col">
                    <%= f.label :name %>
                    <%= f.text_field :name, class: 'custom-text-field' %>
                  </div>
                  <div class="mdl-cell mdl-cell--12-col">
                    <%= f.label :words %>
                    <%= f.text_area :words, class: 'custom-text-area', value: '' %>
                  </div>
                  <div class="mdl-cell mdl-cell--12-col">
                    <%= submit_tag 'Submit', class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--colored' %>
                  </div>
                </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>


  </div>
  <div class="mdl-dialog__actions">
    <button type="button" class="mdl-button close" data-bind="click: finishSetup">
      Done
    </button>
  </div>
</dialog>

app/views/home/_transcript.html.erb
<dialog class="mdl-dialog" id="transcript-dialog">
  <h4 class="mdl-dialog__title mdl-typography--text-center">Transcript</h4>
  <div class="mdl-dialog__content mdl-typography--text-left">

    <ul class="demo-list-three mdl-list" data-bind="foreach: dialogues">
      <li class="mdl-list__item mdl-list__item--three-line dialogue-line">
        <span class="mdl-list__item-primary-content">
          <i class="material-icons mdl-list__item-avatar">person</i>
          <span data-bind="text: user"></span>
          <span class="mdl-list__item-text-body">
            <span data-bind="text: sentence"></span>
            (<span data-bind="visible: wordDetected != 'false', text: wordDetected"></span>)
          </span>

          </span>
        </span>
      </li>
    </ul>
  </div>
  <div class="mdl-dialog__actions">

    <button type="button" class="mdl-button close" data-bind="click: finishSetup">
      Done
    </button>
    <a class="mdl-button mdl-js-button mdl-js-ripple-effect" data-bind="attr: {href: '<%= get_dialogues_path(format: 'csv') %>?transcript[id]='+selectedTranscriptId()}">
      <i class="material-icons">save</i>
      save
    </a>
  </div>
</dialog>

app/views/home/index.html.erb
<div class="mdl-grid container">
  <div class="mdl-cell mdl-cell--12-col">
    <h1>Welcome to Chilab Apps.</h1>
    <p>Choose what you want to do.</p>

    <ul>
      <li><a href="<%= smart_conversation_path %>">Smart Conversations</a></li>
    </ul>

  </div>


</div>

app/views/home/smart_conversation.html.erb
<div class="mdl-grid container">
  <%= render 'smart_conversation_setup' %>

  <div class="mdl-cell mdl-cell--12-col document-container">
    <embed class="align-center" src="documents/chilab-start.pdf" width="900px" height="1100px"></embed>
  </div>

  <div id="word-toast" class="mdl-js-snackbar mdl-snackbar">
    <div class="mdl-snackbar__text mdl-typography--display-2"></div>
    <button class="mdl-snackbar__action" type="button"></button>
  </div>

</div>


<%= render 'transcript' %>

<script id="document-template" type="text/x-handlebars-template">
  <embed class="align-center" src="{{url}}" width="800px" height="1100px"></embed>
</script>

app/views/layouts/_header.html.erb
<header class="mdl-layout__header mdl-layout__header--scroll">
  <div class="mdl-layout__header-row">
    <!-- Title -->
    <span class="mdl-layout-title"><a style="color: white; text-decoration: none" href="<%= home_path %>">CHILAB-APPS</a></span>
    <!-- Add spacer, to align navigation to the right -->
    <div class="mdl-layout-spacer"></div>
    <!-- Navigation -->
    <nav class="mdl-navigation">
      <a class="mdl-navigation__link" href="">
        Link
      </a>
    </nav>
  </div>
</header>
<!--<div class="mdl-layout__drawer">-->
  <!--<span class="mdl-layout-title">Title</span>-->
  <!--<nav class="mdl-navigation">-->
    <!--<a class="mdl-navigation__link" href="">Link</a>-->
  <!--</nav>-->
<!--</div>-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChilabApps</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  </head>

  <body>


  <!-- Uses a header that scrolls with the text, rather than staying
  locked at the top -->
  <div class="mdl-layout mdl-js-layout">
    <%= render 'layouts/header' %>
    <main class="mdl-layout__content">
      <div class="page-content">
        <%= yield %>
      </div>
    </main>
  </div>


  </body>
</html>